#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

BASE_ARCH="arm64"
BASE_IMAGE_ENLARGEROOT=10500
BASE_IMAGE_RESIZEROOT=600
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="raspberry"

# Image source
DOWNLOAD_URL_CHECKSUM="https://github.com/bigtreetech/CB1/releases/download/V3.0.0/CB1_Debian12_minimal_kernel6.6_20241219.img.sha256"
DOWNLOAD_URL_IMAGE="https://github.com/bigtreetech/CB1/releases/download/V3.0.0/CB1_Debian12_minimal_kernel6.6_20241219.img.xz"

# export Variables
export BASE_ARCH
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE

export MODULES="base,passwordless_sudo,pkgupgrade(network,cb1config,klipper,node,is_req_preinstall,moonraker,cb1spi,ratos(mainsail,crowsnest,linear_movement_analysis,timelapse,klipperscreen,rpi_mcu,disable-services(hotspot_cb1),dfu-util),password-for-sudo),postrename"
